import { Geist, Geist_Mono ,Roboto  } from "next/font/google";

import "./globals.css";
import Header from "./_components/Header";


import {
  ClerkProvider,

} from '@clerk/nextjs'
import Provider from "./Provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI Travel Planner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
   

   
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <Header/>
        <Provider>
        {children}
        </Provider>
      </body>
    </html>
    </ClerkProvider>
     
  );
}